# from https://github.com/marketplace/actions/run-protolint-with-reviewdog

name: yoheimuta-lint
on: [pull_request]
permissions: write-all
jobs:
  lint:
    name: yoheimuta-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yoheimuta/action-protolint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          filter_mode: nofilter
